source "https://rubygems.org"
ruby "2.2.4"

gem "jsonable"
gem "feedjira"
gem "sinatra"
gem "sinatra-contrib"
gem "unicorn"
gem "haml"
gem "pretty-xml", "0.1.3"
gem "faraday"
gem "rouge"
gem "faraday_middleware"
